from tutorial

ARG AIRFLOW_VERSION=1.10.0
ARG AIRFLOW_HOME=/usr/local/airflow
ARG GROUP_USER=airflow

ENV AIRFLOW_HOME ${AIRFLOW_HOME}
ENV PYTHONPATH ${AIRFLOW_HOME}

COPY . ${AIRFLOW_HOME}/

RUN useradd -ms /bin/bash -d ${AIRFLOW_HOME} airflow \
    && chown -R airflow: ${AIRFLOW_HOME}

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

EXPOSE 8080 5555 8793

USER airflow

WORKDIR ${AIRFLOW_HOME}
